### ISSUE TITLE
add article + video

### ISSUE THREAD

**Issue by brian123214** [ML-Purdue/ml-purdue.github.io#12]
Add article: https://medium.com/@sigaipurdue/3-out-of-many-ways-neuroscience-inspired-machine-learning-ab53fc20e985 

Add interview video
https://youtu.be/4UDgfXdonPE

with transcript:
https://docs.google.com/document/d/1DCsUVkgIuHOGkzOuI8x1mS-Ti1ckWwJTNAJ7f2_Kguc/edit?usp=sharing

**Comment by chiragzq** [comment]
https://github.com/ML-Purdue/ml-purdue.github.io/commit/70e050980f11c2594c369f395cd9292afb5205ee
