### ISSUE TITLE
[URGENT] Update Projects tab

### ISSUE THREAD

**Issue by jacob-zietek** [ML-Purdue/ml-purdue.github.io#2]
Instead of the structure being

Projects/Industry
Projects/Research
Projects/Entrepreneurial

We should have all of them listed on the same page.

We should also have some nice graphics, some pictures of teams, and some information on how to apply to become a project manager (link to https://ml-purdue.github.io/apply/).

**Comment by chiragzq** [comment]
https://github.com/ML-Purdue/ml-purdue.github.io/commit/b829f37cd50fdeac310e94de81a968eaff818ada
