### ISSUE TITLE
[URGENT] Rework Education Tab

### ISSUE THREAD

**Issue by jacob-zietek** [ML-Purdue/ml-purdue.github.io#3]
We don't have a tab that has our current semester offerings, which is social events on Tuesdays and technical events on Thursdays. The Education tab used to have this info, but the reading group and the beginner workshop series are now defunct. We should still have this info somewhere as an archive (and the content should be displayed better), but this section of the website should be replaced with Fall 2023 content.

Maybe a calendar?

**Comment by chiragzq** [comment]
https://github.com/ML-Purdue/ml-purdue.github.io/commit/07bb7687d8cfb036b243d684f762ba3799bc97d4
