### ISSUE TITLE
Update officers info

### ISSUE THREAD

**Issue by jacob-zietek** [ML-Purdue/ml-purdue.github.io#8]
https://www.notion.so/jacob-zietek/Officers-info-b4bcea248bc44afba16ca6b6fad9d58d

Officer info has changed

If a person doesn't have a title then they aren't a part of the officer team for the time being, please remove them

**Comment by chiragzq** [comment]
https://github.com/ML-Purdue/ml-purdue.github.io/commit/a8d10474385a8b2c93f0002d1831afe371bceef9
